### PR TITLE
update 1.6 build with 1.6.629+ support, _msize patch, new doubleperkapply fix

### PR DESCRIPTION
**Pull request by shad0wshayd3**

### CODE REVIEW

**Comment by grantjoy** [comment]
Is there a build of this somewhere we can download while we wait for merge and nexus?

**Comment by SteRichardson** [comment]
@grantjoy you should be able to grab the artifacts from the build (if you're logged into Github), i.e. https://github.com/aers/EngineFixesSkyrim64/actions/runs/3166343010

**Comment by hermyt** [comment]
The artifact build from yesterday is still tossing a 7e error with the GoG skse 2.2.2 version

**Comment by shad0wshayd3** [comment]
@hermyt that's a bug with the GOG build of SKSE, not Engine Fixes.

**Comment by hermyt** [comment]
I suspected it was either an architecture difference with GoG skse or a bug (with that skse version) which is why I mentioned the GoG version.  Does anyone know of the bug being reported to the skse team, I don't notice that there's a github or other reporting option aside from direct email?

**Pull request merged**
