### PR TITLE
Fix crash in CreateArmorNode (callee sub_1401CAFB0)

### PR DESCRIPTION
**Pull request by fgenesis**
[This thing was responsible for about 50% of my crashes. First time ever doing x64 binary fumbling  so sorry if it's messy; feel free to improve.]

Error message:
Unhandled exception at 0x00007FF7F214B5B6 in SkyrimSE.exe: 0xC0000005: Access violation reading location 0x0000000000000130.

The faulting instruction is:
00000001401CB5B6  rdi,qword ptr [r12+130h]
which crashes due to a wrong NULL check for r12 above:
00000001401CB53A  test r12,r12
00000001401CB53D  jz short loc_1401CB5B6

This fix patches the jump so that the faulting block
is skipped if r12 is NULL.
This seems to be the originally intended behavior.

I have no idea what this function does.
The name CreateArmorNode comes from RaceMenu:
https://github.com/expired6978/SKSE64Plugins/blob/f6adf8cd14ffb65dba212ef85cc36093ac86051e/skee/SKEEHooks.cpp#L85
(Which originally appeared in the call stack when I was debugging this)

### CODE REVIEW

**Comment by aers** [comment]
Hi thanks for this. I'll take a look when I have a chance, but I did check the function and you're 100% right about there being an error.

**Comment by fgenesis** [comment]
I might add that i've been playing a couple hours with this fix and my overall crash rate has gone down significantly (from ~10 mins to 1-2 hours). Only problem i've seen that may be be caused by this is that rarely NPCs (and the PC too, at times) become invisible for a few frames. I think that's where it would otherwise crash. It's not a problem for normal playing though. For me the extra stability is totally worth it, and i've had no save corruption either. Quite the opposite, loading saves crashes a lot less, too.

I've posted a DLL on nexusmods with the change, let's see what kind of reports come in, then you can decide how/when to merge this.
Alternatively you could not patch the first jump to skip the 2nd block; but rather just replace the 2nd block to add the proper check for r12. Your choice really, but i figured this was more future compatible or whatever.

**Comment by expired6978** [comment]
Looks like it also needs to check if r12 is a `NiNode`. r12+0x130 is the child array, but it looks like the source of r12 is from `NiArray<NiAVObject*>` which is not guaranteed to be NiNode.

**Comment by aers** [comment]
Merging this but need to do some work to add the AsNode check..

**Pull request merged**
