### PR TITLE
Change AchievementsMods patch address for 1.6.1130

### PR DESCRIPTION
**Pull request by epinter**

### CODE REVIEW

**Comment by aers** [comment]
Do you know if this is the only problem with the new version? I'm not actively devving Skyrim stuff anymore and haven't checked at all.

**Comment by epinter** [comment]
> Do you know if this is the only problem with the new version? I'm not actively devving Skyrim stuff anymore and haven't checked at all.

I didn't test much, but the mod seems to work, savegames load, no crashes on a new save. People are complaining about crashes on load, but I'm not sure if the crashes come from other mods, or if there's some other offset that needs change.

I was trying to use more the make_pattern with match to test some offsets. But for some reason I'm not able to make it work inside patches.cpp, only works on miscpatches.cpp. Anyway, it would be a big change, because  a pattern would be need for every offset, and theres many...

I will play a bit more with the code, I will report if I find any other offset wrong.

**Comment by AndrejAndb** [comment]
> Looks like achievements and savescreenshots are the only causing crashes. I've open another pull request for savescreenshots.

https://github.com/aers/EngineFixesSkyrim64/issues/62
I am also see CTD in 
```
EngineFixes.dll+004C638	test al, al |  ?hk_GetFormByID@patches@@YAPEAVTESForm@RE@@I@Z_4C638)` 
```

I don't know how to fix it yet, I'm trying to test without this patch (`FormCaching`)

**Comment by epinter** [comment]
From my tests, this offset is still valid for 1.6.1170.

**Pull request merged**
